apiVersion: v1
kind: Pod
metadata:
  name: wkopo-healthcheck
  labels:
    type: app
spec:
  containers:
  - name: app
    image: nginx:latest
    livenessProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80